### PR TITLE
CDMS - 150 NETCDF Reader Updates

### PR DESCRIPTION
**Pull request by JordanGethers**
cdms_reader.py is the original doms_reader.py code with additional functionality provided for the user to make each run of the program more customizable. The user may now select, with option flags, whether or whether not they would like to create a CSV, log, or text (holds global attributes) files associated with their original NETCDF file.

The ReadMe associated with this file has also been updated to reflect changes in the program.

### CODE REVIEW

**Comment by JordanGethers** [comment]
When I run the code in my linux environment, there are some harmless warning messages (pertaining to numPy and occasionally variable conversion) I wanted to ask for approval or suggestions before suppressing any warning messages (if at all).

**Comment by ngachung** [comment]
Thank you, @JordanGethers!

Please reference https://issues.apache.org/jira/projects/SDAP/issues/SDAP-390 as CDMS Jira is restricted and not public.
Please also update CHANGELOG.md
It's great that the dependent libraries are provided in the readme, but please also include requirements.txt or conda-requirements.txt so that users can easily set up env for using the reader.

**Comment by ngachung** [comment]
Sorry for the confusion @JordanGethers. Yes, the github repository is public, but the CDMS JIRA is restricted. Please push all your changes to your forked repo, but where you've referenced CDMS - 150, e.g. in the pull request title, please replace with SDAP-390: Match up NETCDF Reader Updates. Branch name of SDAP-XXX should be SDAP-390. Thank you!

**Comment by ngachung** [comment]
This PR has been superseded by https://github.com/apache/incubator-sdap-nexus/pull/178

**Pull request closed without merging**
