### PR TITLE
SDAP-162 - Create build for nexus-webapp

### PR DESCRIPTION
**Pull request by joshgarde**
Initial build pipeline work with GitHub Actions. Tested with forked repo: https://github.com/joshgarde/incubator-sdap-nexus/actions

### CODE REVIEW

**Comment by skorper** [comment]
Another thought -- what about the version in the openapi.yml file? It would be nice to version that automatically as well, though maybe that's a task for another time

**Comment by joshgarde** [comment]
> I also wonder if we should document the new development process now that it has changed. For example, we have been opening PRs against the master branch, but I think now with your workflow we should open PRs against the develop branch
Perhaps this needs to be part of a larger documentation overhaul ticket? The current documentation seems to be outdated overall with where the project is right now

> Another thought -- what about the version in the openapi.yml file? It would be nice to version that automatically as well, though maybe that's a task for another time
That can be added to this ticket. It would just require a small change

**Comment by skorper** [comment]
It looks like 88aa028 caused the build to break

**Comment by joshgarde** [comment]
Yep - I was experimenting with a few solutions. The build's now passing - https://github.com/joshgarde/incubator-sdap-nexus/runs/4051377910

**Comment by skorper** [comment]
Can you explain how the versioning works now for the openapi.yml file?

**Comment by joshgarde** [comment]
Yes - the versioning for the openapi.yml now tracks the Docker version. The main version file in `docker/` gets bumped first and that version change gets reflected into the `openapi.yml`. I thought it would make sense to tie API spec versioning to the main nexus-webapp distribution, but it can be changed to track `analysis` instead

**Comment by joshgarde** [comment]
Now that I'm thinking more about it however, since the `openapi.yml` file remains static until an API update and it's not dynamically generated, perhaps it's better to keep that manually versioned so that we can properly follow semver semantics and document when breaking changes occur?

**Comment by skorper** [comment]
Does the version get bumped and committed back to openapi.yml?

**Comment by joshgarde** [comment]
The commit of the versioning only occurs on `develop` and `master` branches

**Comment by skorper** [comment]
Gotcha, makes sense thanks @joshgarde !

**Review by skorper — APPROVED** [review]

**Review by ngachung — APPROVED** [review]

**Review by skorper — APPROVED** [review]

**Pull request merged**
