### PR TITLE
SDAP-415: Satellite to satellite queries fail if using an L2 dataset

### PR DESCRIPTION
**Pull request by skorper**
Fixed bug where satellite to satellite queries fail if using an L2* dataset. 

This issue was being caused by a bug where secondary satellite tile masks were being incorrectly combined, causing the entire secondary tile to be masked. This is due to the nature of Python masks and the fact that `True` means the value is invalid, meaning a logical_or against an entirely masked np array would result in an entirely masked np array. This issue cropped up when running sat to sat matchup where VIIRS was the secondary dataset. This is because VIIRS contains lots of null values for some variables -- in many cases the entire variable in the tile is masked. This would cause the above issue. 

Simplifying the problem, our old logic was like this:

```python
>>> a = np.ma.masked_array([1.0, 2.0, 3.0, 4.0], mask=[0, 0, 1, 0])
>>> b = np.ma.masked_array([5.0, 6.0, 7.0, 8.0], mask=[1, 1, 1, 1])
>>> np.logical_or(a, b)
masked_array(data=[--, --, --, --],
             mask=[ True,  True,  True,  True],
       fill_value=1e+20,
            dtype=bool)
```

where `True` means drop the value and `False` means keep the value. This is not what we want! We want the inverse logic, where a masked array "or'd" against an entirely masked array  == the first array.

Our new logic is like this:

```python
>>> np.logical_not(np.logical_and(a.mask, b.mask))
array([True, True,  False, True])
```

where `True` == keep the value and `False` means drop the value. 

In addition to the above, made a few small changes:

1. Only query the insitu API for the schema if `parameter_s` is provided
2. Retrieve tiles one-by-one rather than all at once when finding/retrieving data for secondary tiles.
3. If no secondary tiles are found (in sat to sat matchup), handle gracefully and return `[]` rather than letting an error get raised
4. Fixed bug where only the first two variables are considered in the tile mask computed in `get_indices`

Tested like so:

- Tested Shawn's `ASCATB-L2-Coastal` -> `VIIRS_NPP-2018_Heatwave` query locally. It works!
- Manually ran Riley's regression tests -- all passed. NOTE: Only sat to sat run for now. See below.

Please note the following needs to be done before this PR is approved/merged:

1. Run full regression test suite
   - This is not currently possible because the insitu api is down.
3. Run benchmarks for (2) above, to ensure retrieving sat tiles one-by-one is faster than retrieving them all at once.

### CODE REVIEW

**Comment by RKuttruff** [comment]
> Run benchmarks for (2) above, to ensure retrieving sat tiles one-by-one is faster than retrieving them all at once.

Should we also benchmark with the proposed L2 optimizations?

**Comment by skorper** [comment]
> > Run benchmarks for (2) above, to ensure retrieving sat tiles one-by-one is faster than retrieving them all at once.
> 
> Should we also benchmark with the proposed L2 optimizations?

I'd definitely be curious to know the before/after benchmarks with the L2 optimization applied! It's probably not a prerequisite to merging this but still very good know

**Comment by skorper** [comment]
@ngachung I ran Riley's regression tests. These mostly passed, though we did see the duplicate primary issue, which we still haven't found the root cause of. I'm satisfied with those results and confident these changes will not cause any major changes to the existing results validated by our collaborators

**Comment by RKuttruff** [comment]
> @ngachung I ran Riley's regression tests. These mostly passed, though we did see the duplicate primary issue, which we still haven't found the root cause of. I'm satisfied with those results and confident these changes will not cause any major changes to the existing results validated by our collaborators

I'd like to talk to you about the duplicate primary issue. I've isolated (I think) where it happens.

**Comment by skorper** [comment]
Benchmarks!

```bash
/match_spark?secondary=ASCATB-L2-Coastal&primary=VIIRS_NPP-2018_Heatwave&startTime=2018-07-05T00%3A00%3A00Z&endTime=2018-07-05T23%3A59%3A59Z&tt=43200&rt=1000&b=-120,28,-118,30&depthMin=-20&depthMax=10&matchOnce=true&resultSizeLimit=7000&platforms=42
```

Before:

| Run | Total Time  |
| --- | ----------- |
| 1   | 2 m 34.62 s |
| 2   | 2 m 7.80 s  |
| 3   | 2 m 49.44 s |
| 4   | 2 m 31.14 s |
| 5   | 2 m 23.34 s |

Average: 149.268 s
Median: 151.14 s

After:

| Run | Total Time  |
| --- | ----------- |
| 1   | 4 m 17.46 s |
| 2   | 2 m 33.97 s |
| 3   | 2 m 15.90 s |
| 4   | 1 m 57.24 s |
| 5   | 1 m 49.08 s |
| 6   | 1 m 44.58 s |
| 7   | 1 m 28.44 s |
| 8   | 2 m 0.42 s  | 

Average: 135.88625000000002
Median: 118.83000000000001


---

```bash
{{big_data_url}}/match_spark?primary=ASCATB-L2-Coastal&secondary=MUR25-JPL-L4-GLOB-v04.2&startTime=2018-08-01T00%3A00%3A00Z&endTime=2018-08-01T23%3A59%3A59Z&b=-122%2C26%2C-114%2C34&platforms=30&depthMin=-1&depthMax=1&tt=43200&rt=18750&matchOnce=true&resultSizeLimit=0
```

Before:

| Run | Total Time |
| --- | ---------- |
| 1   | 30.97 s    |
| 2   | 17.04 s    |
| 3   | 15.96 s    |
| 4   | 16.61 s    |
| 5   | 16.40 s    | 

Average: 19.395999999999997
Median: 16.61

After:

| Run | Total Time |
| --- | ---------- |
| 1   | 36.92 s    |
| 2   | 26.38 s    |
| 3   | 14.79 s    |
| 4   | 16.55 s    |
| 5   | 16.23 s    | 

Average: 22.174
Median: 16.55

**Review by ngachung — APPROVED** [review]
Lgtm. Thank you!

**Pull request merged**
